import { motion } from 'framer-motion';

const featuresList = [
  {
    icon: '🍽️',
    title: 'AI-Powered Meal Plans',
    description: 'Personalized nutrition plans based on your dietary preferences and goals, generated by our advanced AI.',
  },
  {
    icon: '💪',
    title: 'Custom Fitness Routines',
    description: 'Tailored workout plans that adapt to your progress and fitness level for optimal results.',
  },
  {
    icon: '📊',
    title: 'Progress Tracking',
    description: 'Comprehensive tracking of your fitness journey with visual charts and data-driven insights.',
  },
  {
    icon: '🤖',
    title: 'DeepSeek AI Integration',
    description: 'Cutting-edge artificial intelligence that learns your preferences and optimizes your fitness experience.',
  },
  {
    icon: '📱',
    title: 'Seamless Experience',
    description: 'A smooth, single-page design that makes navigation intuitive and enjoyable.',
  },
  {
    icon: '🔄',
    title: 'Continuous Adaptation',
    description: 'Your plans evolve as you progress, ensuring you always have the right challenge level.',
  },
];

const Features = () => {
  return (
    <div className="container mx-auto px-4 py-16">
      <motion.div
        initial={{ opacity: 0 }}
        whileInView={{ opacity: 1 }}
        transition={{ duration: 0.5 }}
        viewport={{ once: true }}
        className="text-center mb-16"
      >
        <h2 className="text-4xl font-bold mb-4">
          <span className="text-primary">Powerful</span> Features
        </h2>
        <p className="text-xl text-gray-300 max-w-2xl mx-auto">
          OniFit combines cutting-edge AI technology with fitness expertise to deliver a personalized experience.
        </p>
      </motion.div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
        {featuresList.map((feature, index) => (
          <motion.div
            key={index}
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: index * 0.1 }}
            viewport={{ once: true }}
            className="bg-secondary-light p-6 rounded-lg hover:shadow-lg transition-all duration-300 hover:shadow-primary/20 border border-gray-800 hover:border-primary/30"
          >
            <div className="text-4xl mb-4">{feature.icon}</div>
            <h3 className="text-xl font-semibold mb-2 text-white">{feature.title}</h3>
            <p className="text-gray-400">{feature.description}</p>
          </motion.div>
        ))}
      </div>

      <motion.div
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, delay: 0.3 }}
        viewport={{ once: true }}
        className="mt-16 text-center"
      >
        <div className="inline-block bg-secondary-light border border-gray-800 rounded-lg p-4">
          <p className="text-gray-400">
            <span className="text-primary font-semibold">All features</span> are included in your subscription
          </p>
        </div>
      </motion.div>
    </div>
  );
};

export default Features; 